In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
df=pd.read_csv("C:/Users/ADMIN/Downloads/Innovox-Audio-Pricing-All-Levels-March-2021.csv",delimiter=',', names=list(range(10)))

In [ ]:
df

In [3]:
df.dropna(thresh=4,inplace=True)

In [4]:
df.dropna(axis=1,how='all',inplace=True)

In [ ]:
df.columns=df.iloc[0]

In [ ]:
df

In [5]:
df1 = pd.DataFrame(df, index=range(27,75))

In [ ]:
df

In [6]:
df1.dropna(thresh=4, inplace=True)

In [ ]:
df1.dropna(axis=1, how='all', inplace=True)

In [ ]:
df1

In [ ]:
Premium -5%

In [ ]:
df1["Premium -5% "] = df1["Premium -5% "].fillna('-')

In [ ]:
df1 = df1[df1["Premium -5% "].str.match('[^a-zA-Z]')]

In [ ]:
df1["Premium -5% "]=df1["Premium -5% "].replace("-", "", regex=True)

In [ ]:
df1

In [7]:
df2 = pd.DataFrame(df, index=range(76, 82))

In [ ]:
df2

In [10]:
df2.columns=df2.iloc[0]

In [ ]:
df2

In [15]:
df2

76,Model,Category,Description,MSRP,Std. Dealer,Value -3%,Premium -5%,Partner -10%
77,SHMF-1WM,SPKR FRAME,"Slim single display frame 3.50"" D 9.00"" H","$1,097",$658,$638,$625,$592
78,SHMF-2WM,SPKR FRAME,"Slim dual display frame 3.50"" D 9.00"" H","$1,372",$823,$798,$782,$741
79,SSCMP,CAMERA POCKET,Sliding camera pocket module for slim frames,$463,$278,$270,$264,$250
80,SMSM-6,SPKR,"Single 6"" subwoofer for slim frames",$512,$307,$298,$292,$276
81,SMSM-2x6,SPKR,"Dual 6"" subwoofer for slim frames",$862,$517,$501,$491,$465

In [ ]:
df2['Description'] = df2[2] + df2[3]

In [8]:
df2[2] = df2[2].fillna('Description')

In [12]:
df2.dropna(axis=1,thresh=2,inplace=True)

In [ ]:
df2

In [14]:
df2 = df2[df2["MSRP "].str.match('[^a-zA-Z]')]

In [ ]:
df2

In [16]:
df3 = pd.DataFrame(df, index=range(82, 102))

In [27]:
df3

83,Model,Display Size,Description,MSRP,Std. Dealer,Value -3%,Premium -5%,Partner -10%
84,Synergy Compact,"49"" 75""",Huddle & Collaboration Space Solution. featuri...,"$2,647","$1,588","$1,540","$1,509","$1,429"
85,Synergy Compact T-M,NaN,"Huddle & Collaboration Space Solution, featuri...","$3,009","$1,805","$1,751","$1,715","$1,625"
86,Flex Companion 2x5,LF Extension,"2x5"" 200W powered subwoofer for use with Syner...","$1,061",$636,$617,$605,$573
87,Flex Companion 2x6,LF Extension,"2x6"" 200W powered subwoofer for use with Syner...","$1,112",$667,$647,$634,$600
90,FPH1 3250,32' 50',1 channel horizontal video display loudspeaker...,$702,$421,$408,$400,$379
91,FPH1 5070,"50"" 70""",NaN,$827,$496,$481,$471,$446
92,FPH1 7585,"75"" 85'",NaN,$950,$570,$553,$542,$513
93,FPH2 3250,"32"" - 50'",2 channel horizontal video display loudspeaker...,$985,$591,$573,$561,$532
94,FPH2 5070,"50' 70""",NaN,"$1,160",$696,$675,$661,$626
95,FPH2 7585,"75"" - 85""",NaN,"$1,333",$800,$776,$760,$720
96,FPH3 7585,"75"" 85'",3 channel horizontal video display loudspeaker...,"$1,582",$949,$921,$902,$854
99,FPV2 3250,"32' 50""",2 channel vertical video display loudspeaker n...,"$1,318",$791,$767,$751,$712
100,FPV2 5070,"50"" 70""",NaN,"$1,550",$930,$902,$884,$837
101,FPV2 7585,"75"" 85""",NaN,"$1,783","$1,070","$1,038","$1,017",$963

In [25]:
df3.isnull().sum()

83
Model            0
Display Size     1
Description      6
MSRP             0
Std. Dealer      0
Value -3%        0
Premium -5%      0
Partner -10%     0
dtype: int64

In [18]:
df3.dropna(thresh=2,inplace=True)

In [19]:
df3.dropna(axis=1,how='all', inplace=True)

In [20]:
df3.columns=df3.iloc[0]

In [ ]:
df3

In [26]:
df3 = df3[df3["MSRP "].str.match('[^a-zA-Z]')]

In [ ]:
df3

In [63]:
df4 = pd.DataFrame(df, index=range(102, 106))

In [64]:
df4.dropna(thresh=2,inplace=True)

In [65]:
df4.dropna(axis=1,how='all', inplace=True)

In [66]:
df4.columns=df4.iloc[1]

In [70]:
df4 = df4[df4["MSRP "].str.match('[^a-zA-Z]')]

In [69]:
df4["MSRP "]=df4["MSRP "].fillna("-")

In [71]:
df4

103,Model,Catagory,NaN,Description,MSRP,Std. Dealer,Value -3%,Premium -5%,Partner -10%
102,FlexPrecision,Power Options,/,Low-Frequency extension / Options,-,NaN,NaN,NaN,NaN
104,Flex P,Amplifier,NaN,2x200W Class D amplifier *,$590,$354,$343,$336,$319
105,Flex PX,Amplifier,NaN,2x200W Class D amplifier w/DSP,"$1,278",$767,$744,$729,$690

In [76]:
df5 = pd.DataFrame(df, index=range(108, 110))

In [78]:
df5.dropna(thresh=2,inplace=True)

In [80]:
df5.dropna(axis=1,how='all', inplace=True)

In [84]:
df5.columns=df5.iloc[0]

In [86]:
df5 = df5[df5["MSRP "].str.match('[^a-zA-Z]')]

In [87]:
df5

108,Model Display Size Description,MSRP,Std Dealer Value -3%,Premium -5%,Partner -10%
109,"FSH2 3265 32"" 65' 2 channel horizontal video d...",$905,$543 $527,$516,$489

In [110]:
df6 = pd.DataFrame(df, index=range(111, 123))

In [111]:
df6.dropna(thresh=2,inplace=True)

In [112]:
df6.dropna(axis=1,how='all', inplace=True)

In [114]:
df6.columns=df6.iloc[0]

In [115]:
df6 = df6[df6["MSRP "].str.match('[^a-zA-Z]')]

In [116]:
df6

111,Model,Display Size,Description,MSRP,Std Dealer,Value -3%,Premium -5%,Partner -10%
112,FSV2 3265,32' 65',2 channel vertical video display loudspeaker n...,"$1,187",$712,$691,$676,$641
115,FFH1.25 5070,50' 70',1 channel horizontal line array video display ...,"$1,020",$612,$594,$581,$551
116,FFH1 25 7085,"70"" 85""",NaN,"$1,255",$753,$730,$715,$678
117,FFH1 .25 8698,"86"" 98'",NaN,"$1,372",$823,$798,$782,$741
118,FFH1.25 98 Plus,"98"" and larger",NaN,"$1,628",$977,$948,$928,$879
119,FFH1 .50 5070,50' 70',1 channel horizontal line array video display ...,"$1,020",$612,$594,$581,$551
120,FFH1.50 07085,"70"" 85'",NaN,"$1,255",$753,$730,$715,$678
121,FFH1.50 8698,"86"" 98'",NaN,"$1,372",$823,$798,$782,$741
122,FFH1 .50 98 Plus,"98"" and larger",NaN,"$1,628",$977,$948,$928,$879

In [152]:
df7 = pd.DataFrame(df, index=range(123, 129))

In [153]:
df7.dropna(thresh=2,inplace=True)

In [154]:
df7.dropna(axis=1,how='all', inplace=True)

In [155]:
df7.columns=df7.iloc[0]

In [156]:
df7 = df7[df7["Value -3% "].str.match('[^a-zA-Z]')]

In [157]:
df7

124,Model,Display Size Description,MSRP Std,Dealer,Value -3%,Premium -5%,Partner -10%
125,FFV2 5070,"50"" 70"" 2 channel vertical line array video di...","$1,995","$1,197","$1,161","$1,137","$1,077"
126,FFV2 7085,"70"" - 85""","$2,328","$1,397","$1,355","$1,327","$1,257"
127,FFV2 8698,"86"" - 98""","$2,662","$1,597","$1,549","$1,517","$1,437"
128,FFV2 98 Plus,"98"" and larger","$2,995","$1,797","$1,743","$1,707","$1,617"

In [146]:
df8 = pd.DataFrame(df, index=range(129, 134))

In [147]:
df8.dropna(thresh=2,inplace=True)

In [148]:
df8.dropna(axis=1,how='all', inplace=True)

In [149]:
df8.columns=df8.iloc[0]

In [150]:
df8 = df8[df8["Value -3% "].str.match('[^a-zA-Z]')]

In [151]:
df8

130,Model,Catagory,NaN,Description,MSRP,Std Dealer,Value -3%,Premium -5%,Partner -10%
131,Flex P,Amplifier,2x200W,Class D amplifier *,$590,$354,$343,$336,$319
132,Flex PX,Amplifier,2x200W,Class D amplifier w/DSP,"$1,278",$767,$744,$729,$690
133,Flex PXD,Amplifier,2x200W,Class D amplifier w/DSP & Dante **,"$1,658",$995,$965,$945,$896

In [168]:
df9 = pd.DataFrame(df, index=range(134, 137))

In [170]:
df9.dropna(thresh=2,inplace=True)

In [172]:
df9.dropna(axis=1,how='all', inplace=True)

In [173]:
df9.columns=df9.iloc[0]

In [174]:
df9 = df9[df9["Value -3% "].str.match('[^a-zA-Z]')]

In [175]:
df9

134,Model,Category,Description,MSRP,Std Dealer,Value -3%,Premium -5%,Partner -10%
135,FlexArray,SPKR,"Large powered line array, with steered dipole ...","$27,987","$16,792","$16,288","$15,952","$15,113"
136,FlexArray Compact,SPKR,"Compact powered line array, with steered dipol...","$14,295","$8,577","$8,320","$8,148","$7,719"

In [176]:
df10 = pd.DataFrame(df, index=range(144, 465))

In [179]:
df10.dropna(thresh=2,inplace=True)

In [181]:
df10.dropna(axis=1,how='all', inplace=True)

In [187]:
df10.columns=df10.iloc[0]

In [189]:
df10 = df10[df10["Value -3% "].str.match('[^a-zA-Z]')]

In [190]:
df10

148,Model,Catagory,Description,MSRP,Std Dealer,Value -3%,Premium -5%,Partner -10%
149,Flex Companion 2x5,LF Extension,"2x5"" 200W powered low-frequency extension, sur...","$1,060",$636,$617,$604,$572
150,Flex Companion 2x6,LF Extension,"2x6"" 200W powered low-frequency extension, sur...","$1,112",$667,$647,$634,$600
152,CLA-935 blk,SPKR,"x3.5"" mid, 9 ribbon HF 120Hx35V","$2,643","$1,586","$1,538","$1,506","$1,427"
153,CLA-935 wht,SPKR,"9 x 3.5"" mid, 9 ribbon HF 120Hx35V","$2,643","$1,586","$1,538","$1,506","$1,427"
154,CLA-950 blk,SPKR,"x3.5"" mid, 9 ribbon HF 120Hx50V","$2,643","$1,586","$1,538","$1,506","$1,427"
...,...,...,...,...,...,...,...,...
460,SCS-318 blk,CRD SUB,Compact powered 3 element cardioid subwoofer 3...,"$9,826","$5,896","$5,719","$5,601","$5,306"
461,SCS-318 wht,CRD SUB,Compact powered 3 element cardioid subwoofer 3...,"$9,826","$5,896","$5,719","$5,601","$5,306"
462,SCS-318 cst,CRD SUB,Compact powered 3 element cardioid subwoofer 3...,"$10,809","$6,485","$6,153","$6,026","$5,709"
463,SCS-321 blk,CRD SUB,Compact powered 3 element cardioid subwoofer 3...,"$9,826","$9,250.00","$8,973","$8,788","$8,325"
464,SCS-321 wht,CRD SUB,Compact powered 3 element cardioid subwoofer 3...,"$9,826","$9,250.00","$8,973","$8,788","$8,325"

In [219]:
df11 = pd.DataFrame(df, index=range(465, 501))

In [220]:
df11.dropna(thresh=2,inplace=True)

In [221]:
df11.dropna(axis=1,how='all', inplace=True)

In [222]:
df11.columns=df11.iloc[0]

In [223]:
df11 = df11[df11["Value -3% "].str.match('[^a-zA-Z]')]

In [224]:
df11

465,Model,Category,NaN,Description,MSRP,Std. Dealer,Value -3%,Premium -5%,Partner -10%
466,SLF112 blk,SUB,"Compact, sealed sub bass enclosure 1x12'",NaN,"$1,973","$1,184","$1,148","$1,125","$1,066"
467,SLF112 wht,SUB,"Compact, sealed sub bass enclosure 1x12'",NaN,"$1,973","$1,184","$1,148","$1,125","$1,066"
468,SLF112 cst,SUB,"Compact, sealed sub bass enclosure 1x12'",NaN,"$2,171","$1,302","$1,263","$1,237","$1,172"
469,SLF112P blk,SUB,"Compact, powered, sealed sub bass enclosure 1X...",NaN,"$3,902","$2,341","$2,271","$2,224","$2,107"
470,SLF112P wht,SUB,"Compact, powered, sealed sub bass enclosure 1X...",NaN,"$3,902","$2,341","$2,271","$2,224","$2,107"
471,SLF112P cst,SUB,"Compact, powered, sealed sub bass enclosure 1x...",NaN,"$4,292","$2,575","$2,498","$2,446","$2,318"
472,SLF212 blk,SUB,"Compact, sealed sub bass enclosure 2x12'",NaN,"$3,107","$1,864","$1,808","$1,771","$1,678"
473,SLF212 wht,SUB,"Compact, sealed sub bass enclosure 2x12'",NaN,"$3,107","$1,864","$1,808","$1,771","$1,678"
474,SLF212 cst,SUB,"Compact, sealed sub bass enclosure 2x12""",NaN,"$3,417","$2,050","$1,989","$1,948","$1,845"
475,SLF212P blk,SUB,"Compact, powered, sealed sub bass enclosure 2x...",NaN,"$5,035","$3,021","$2,930","$2,870","$2,719"
476,SLF212P wht,SUB,"Compact, powered, sealed sub bass enclosure 2x...",NaN,"$5,035","$3,021","$2,930","$2,870","$2,719"
477,SLF212P cst,SUB,"Compact, powered, sealed sub bass enclosure 2x...",NaN,"$5,539","$3,323","$3,223","$3,157","$2,991"
478,SLF115 blk,SUB,"Compact, sealed sub bass enclosure 1x15'",NaN,"$2,030","$1,218","$1,181","$1,157","$1,096"
479,SLF115 wht,SUB,"Compact, sealed sub bass enclosure 1x15'",NaN,"$2,030","$1,218","$1,181","$1,157","$1,096"
480,SLF115 cst,SUB,"Compact, sealed sub bass enclosure 1x15""",NaN,"$2,233","$1,340","$1,300","$1,273","$1,206"
481,SLF115P blk,SUB,"Compact, powered, sealed sub bass enclosure 1x...",NaN,"$3,792","$2,275","$2,207","$2,161","$2,048"
482,SLF115P wht,SUB,"Compact, powered, sealed sub bass enclosure 1x...",NaN,"$3,792","$2,275","$2,207","$2,161","$2,048"
483,SLF115P cst,SUB,"Compact, powered, sealed sub bass enclosure 1x...",NaN,"$4,171","$2,503","$2,427","$2,377","$2,252"
484,SLF215 blk,SUB,"Compact, sealed sub bass enclosure 2x15""",NaN,"$3,542","$2,125","$2,061","$2,019","$1,913"
485,SLF215 wht,SUB,"Compact, sealed sub bass enclosure 2x15""",NaN,"$3,542","$2,125","$2,061","$2,019","$1,913"
486,SLF215 cst,SUB,"Compact, sealed sub bass enclosure 2x15""",NaN,"$3,896","$2,338","$2,267","$2,221","$2,104"
487,SLF215P blk,SUB,"Compact, powered, sealed sub bass enclosure 2x...",NaN,"$5,470","$3,282","$3,184","$3,118","$2,954"
488,SLF215P wht,SUB,"Compact, powered, sealed sub bass enclosure 2x...",NaN,"$5,470","$3,282","$3,184","$3,118","$2,954"
489,SLF215P cst,SUB,"Compact, powered, sealed sub bass enclosure 2x...",NaN,"$6,017","$3,610","$3,502","$3,430","$3,249"
490,SLF118 blk,SUB,"Compact, sealed sub bass enclosure 1x18""",NaN,"$2,638","$1,583","$1,536","$1,504","$1,425"
491,SLF118 wht,SUB,"Compact, sealed sub bass enclosure 1x18'",NaN,"$2,638","$1,583","$1,536","$1,504","$1,425"
492,SLF118 cst,SUB,"Compact, sealed sub bass enclosure 1x18""",NaN,"$2,902","$1,741","$1,689","$1,654","$1,567"
493,SLF118P blk,SUB,"Compact, powered, sealed sub bass enclosure 1x...",NaN,"$5,817","$3,490","$3,385","$3,316","$3,141"
494,SLF118P wht,SUB,"Compact, powered, sealed sub bass enclosure 1x...",NaN,"$5,817","$3,490","$3,385","$3,316","$3,141"
495,SLF118P cst,SUB,"Compact, powered, sealed sub bass enclosure 1x...",NaN,"$6,398","$3,839","$3,724","$3,647","$3,455"
496,SLF218 blk,SUB,"Compact, sealed sub bass enclosure 2X18""",NaN,"$4,033","$2,420","$2,347","$2,299","$2,178"
497,SLF218 wht,SUB,"Compact, sealed sub bass enclosure 2X18""",NaN,"$4,033","$2,420","$2,347","$2,299","$2,178"
498,SLF218 cst,SUB,"Compact, sealed sub bass enclosure 2X18'",NaN,"$4,437","$2,662","$2,582","$2,529","$2,396"
499,SLF218P blk,SUB,"Compact, powered, sealed sub bass enclosure 2x...",NaN,"$7,212","$4,327","$4,197","$4,111","$3,894"
500,SLF218P wht,SUB,"Compact, powered, sealed sub bass enclosure 2x...",NaN,"$7,212","$4,327","$4,197","$4,111","$3,894"

In [255]:
df12 = pd.DataFrame(df, index=range(501, 524))

In [256]:
df12.dropna(thresh=2,inplace=True)

In [257]:
df12.dropna(axis=1,how='all', inplace=True)

In [258]:
df12.columns=df12.iloc[0]

In [260]:
df12 = df12[df12["Value -3% "].str.match('[^a-zA-Z]')]

In [259]:
df12.columns=df12.iloc[12]

In [261]:
df12

514,Dual woofer designs,available Category,Description,MSRP Std.,Dealer,Value -3%,Premium -5%,Partner -10%
502,SB-115 blk,SUB,"Compact X 15"" subwoofer, 1000 Watts RMS (AES 2...","$2,268","$1,361","$1,320","$1,293","$1,225"
503,SB-115 wht,SUB,"Compact 15"" subwoofer, 1000 Watts RMS (AES 2),...","$2,268","$1,361","$1,320","$1,293","$1,225"
504,SB-115 cst,SUB,"Compact 1 x 15"" subwoofer, 1000 Watts RMS (AES...","$2,495","$1,497","$1,456","$1,429","$1,361"
505,SB-118 blk,SUB,"Compact 18"" subwoofer, 1200 Watts RMS (AES 2),...","$2,603","$1,562","$1,515","$1,484","$1,405"
506,SB-118 wht,SUB,"Compact 18"" subwoofer, 1200 Watts RMS (AES 2),...","$2,603","$1,562","$1,515","$1,484","$1,405"
507,SB-118 cst,SUB,"Compact 18"" subwoofer, 1200 Watts RMS (AES 2),...","$2,863","$1,718","$1,671","$1,640","$1,562"
508,SB-115PA blk,SUB,"Compact 15' subwoofer, 2 x1500W w/ a powered &...","$4,197","$2,518","$2,442","$2,392","$2,266"
509,SB-115PA wht,SUB,"Compact 15"" subwoofer, 2 x1500W w/ a powered &...","$4,197","$2,518","$2,442","$2,392","$2,266"
510,SB-115PA cst,SUB,"Compact x 15"" subwoofer, 2x1500W w/ a powered ...","$4,616","$2,770","$2,687","$2,631","$2,493"
511,SB-118PA blk,SUB,"Compact 18"" subwoofer, 2 x1500W w/ a powered &...","$4,345","$2,707","$2,529","$2,477","$2,347"
512,SB-118PA wht,SUB,"Compact 18"" subwoofer, 2 x1500W w/ a powered &...","$4,345","$2,707","$2,529","$2,477","$2,347"
513,SB-118PA cst,SUB,"Compact x 18"" subwoofer, 2 x1500W w/ a powered...","$4,963","$2,978","$2,888","$2,829","$2,680"
515,SBA-115 blk,SUB,"Compact arrayable 15"" subwoofer, 1400 watts RM...","$2,573","$1,544","$1,498","$1,467","$1,390"
516,SBA-115 wht,SUB,"Compact arrayable 15"" subwoofer, 1400 watts RM...","$2,573","$1,544","$1,498","$1,467","$1,390"
517,SBA-115 cst,SUB,"Compact arrayable 15"" subwoofer, 1400 watts RM...","$2,831","$1,698","$1,652","$1,621","$1,544"
518,SBA-118 blk,SUB,"Compact arrayable 18"" subwoofer, 1600 watts RM...","$2,960","$1,776","$1,723","$1,687","$1,598"
519,SBA-118 wht,SUB,"Compact arrayable 18"" subwoofer, 1600 watts RM...","$2,960","$1,776","$1,723","$1,687","$1,598"
520,SBA-118 cst,SUB,"Compact arrayable 18"" subwoofer, 1600 watts RM...","$3,256","$1,954","$1,900","$1,865","$1,776"
521,SBA-218 blk,SUB,"Compact arrayable 2x 18"" subwoofer, 3200 watts...","$4,840","$2,904","$2,817","$2,759","$2,613"
522,SBA-218 wht,SUB,"Compact arrayable 2 18"" subwoofer, 3200 watts ...","$4,840","$2,904","$2,817","$2,759","$2,613"
523,SBA-218 cst,SUB,"Compact arrayable 18"" subwoofer, 3200 watts RM...","$5,324","$3,194","$3,107","$3,049",NaN

In [278]:
df13 = pd.DataFrame(df, index=range(524, 543))

In [281]:
df13.dropna(thresh=2,inplace=True)

In [268]:
df13.dropna(axis=1,how='all', inplace=True)

In [271]:
df13.columns=df13.iloc[0]

In [274]:
df13 = df13[df13["Value -3% "].str.match('[^a-zA-Z]')]

In [282]:
df13

,0,1,2,3,4,5,6,7,8
524,Model,Category,NaN,Description,MSRP Std,Dealer,Value -3%,Premium -5%,Partner -10%
525,HLA-SBA-16 F/B blk,ACC,Fly hardware SBA-115 behind HLA-16,NaN,"$2,336","$1,401","$1,359","$1,331","$1,261"
526,HLA-SBA-16 F/B wht,ACC,Fly hardware SBA-115 behind HLA-16,NaN,"$2,336","$1,401","$1,359","$1,331","$1,261"
527,HLA-SBA-16 F/B cst,ACC,Fly hardware SBA-115 behind HLA-16,NaN,"$2,569","$1,542","$1,500","$1,471","$1,401"
528,HLA-SBA-16 T/B blk,ACC,Fly hardware HLA-16 below SBA-115,NaN,"$2,336","$1,401","$1,359","$1,331","$1,261"
529,HLA-SBA-16 T/B wht,ACC,Fly hardware HLA-16 below SBA-115,NaN,"$2,336","$1,401","$1,359","$1,331","$1,261"
530,HLA-SBA-16 T/B cst,ACC,Fly hardware HLA-16 below SBA-115,NaN,"$2,569","$1,542","$1,500","$1,471","$1,401"
531,HLA-SBA-20 F/B blk,ACC,Fly hardware SBA-118 behind HLA-20,NaN,"$2,572","$1,543","$1,497","$1,466","$1,389"
532,HLA-SBA-20 F/B wht,ACC,Fly hardware SBA-118 behind HLA-20,NaN,"$2,572","$1,543","$1,497","$1,466","$1,389"
533,HLA-SBA-20 F/B cst,ACC,Fly hardware SBA-118 behind HLA-20,NaN,"$2,829","$1,697","$1,651","$1,620","$1,543"
534,HLA-SBA-20 T/B blk,ACC,Fly hardware HLA-20 below SBA-118,NaN,"$2,572","$1,543","$1,497","$1,466","$1,389"
535,HLA-SBA-20 T/B wht,ACC,Fly hardware HLA-20 below SBA-118,NaN,"$2,572","$1,543","$1,497","$1,466","$1,389"
536,HLA-SBA-20 T/B cst,ACC,Fly hardware HLA-20 below SBA-118,NaN,"$2,829","$1,697","$1,651","$1,620","$1,543"
537,SBA-118 Fly Bar blk,ACC,Suspends an array of up to six SBA-118,NaN,"$2,336","$1,401","$1,359","$1,331","$1,261"
538,SBA-118 Fly Bar wht,ACC,Suspends an array of up to six SBA-118,NaN,"$2,336","$1,401","$1,359","$1,331","$1,261"
539,SBA-118 Fly Bar cst,ACC,Suspends an array of up to six SBA-118,NaN,"$2,569","$1,542","$1,500","$1,471","$1,401"
540,SBA-218 Fly Bar blk,ACC,Suspends an array of up to six SBA-218,NaN,"$2,488","$1,493","$1,448","$1,418","$1,344"
541,SBA-218 Fly Bar wht,ACC,Suspends an array of up to six SBA-218,NaN,"$2,488","$1,493","$1,448","$1,418","$1,344"

In [300]:
df14 = pd.DataFrame(df, index=range(543, 590))

In [301]:
df14.dropna(thresh=2,inplace=True)

In [302]:
df14.dropna(axis=1,how='all', inplace=True)

In [303]:
df14.columns=df14.iloc[0]

In [304]:
df14 = df14[df14["Dealer Value "].str.match('[^a-zA-Z]')]

In [305]:
df14

543,Model,Category,Description,MSRP Std.,Dealer Value,-3% Premium,-5%,Partner -10%
544,CA-2,AMP,2-in/2-out DSP with 350 W per channel in compa...,"$1,190",$728,$706,$692,$655
545,X8 DSP+DANTE,AMP,"8 X 1600 watts into 8 ohms, with DSP+DANTE","$14,972","$8,983",NA,NA,NA
546,X8 DSP+ETH,AMP,"8 X 1600 watts into 8 ohms, with DSP+ETH","$13,858","$8,315",NA,NA,NA
547,X4 DSP+DANTE,AMP,"4 X 1600 watts into 8 ohms, with DSP+DANTE","$9,738","$5,843",NA,NA,NA
548,X4 DSP+ETH,AMP,"4 X 1600 watts into 8 ohms, with DSP+ETH","$8,616","$5,170",NA,NA,NA
549,X4L DSP+DANTE,AMP,"4 X 4800 watts into 8 ohms, with DSP+DANTE","$16,022","$9,613",NA,NA,NA
550,X4L DSP+ETH,AMP,"4 X 4800 watts into 8 ohms, with DSP+ETH","$14,920","$8,952",NA,NA,NA
551,Duecanali 6404 DSP+DANTE,AMP,"2 X 1800 watts into 8 ohms, with DSP+DANTE","$4,140","$2,484",NA,NA,NA
552,Duecanali 4804 DSP+DANTE,AMP,"2 X 1250 watts into 8 ohms, with DSP+DANTE","$3,342","$2,005",NA,NA,NA
553,Duecanali 4804,AMP,2 X 1250 watts into 8 ohms,"$2,972","$1,783",NA,NA,NA
554,Duecanali 1604 DSP+DANTE,AMP,"2 X 800 watts into 8 ohms, with DSP+DANTE","$2,246","$1,348",NA,NA,NA
555,Duecanali 1604,AMP,2 X 800 watts into 8 ohms,"$1,875","$1,125",NA,NA,NA
556,Duecanali 804 DSP+DANTE,AMP,"2 X 400 watts into 8 ohms, with DSP+DANTE","$1,875","$1,125",NA,NA,NA
557,Duecanali 804,AMP,2 X 400 watts into ohms,"$1,505",$921,NA,NA,NA
558,Quattrocanali 8804 DSP+DANTE,AMP,"4 X 1600 watts into 8 ohms, with DSP+DANTE","$4,645","$2,787",NA,NA,NA
559,Quattrocanali 4804 DSP+DANTE,AMP,"4 X 1200 watts into 8 ohms, with DSP+DANTE","$3,868","$2,321",NA,NA,NA
560,Quattrocanali 4804,AMP,4 X 1200 watts into 8 ohms,"$3,276","$1,965",NA,NA,NA
561,Quattrocanali 2404 DSP+DANTE,AMP,"4 X 600 watts into 8 ohms, with DSP+DANTE","$2,987","$1,792",NA,NA,NA
562,Quattrocanali 2404,AMP,4 X 600 watts into 8 ohms,"$2,400","$1,440",NA,NA,NA
563,Quattrocanali 1204 DSP+DANTE,AMP,"4 X 300 watts into 8 ohms, with DSP+DANTE","$2,400","$1,440",NA,NA,NA
564,Quattrocanali 1204,AMP,4 X 300 watts into ohms,"$1,812","$1,087",NA,NA,NA
565,Ottocanali 12K4 DSP+DANTE,AMP,"8 X 750 watts into 8 ohms, with DSP+DANTE","$8,590","$5,154",NA,NA,NA
566,Ottocanali 12K4,AMP,8 X 750 watts into ohms,"$7,704","$4,622",NA,NA,NA
567,Ottocanali 8K4 DSP+DANTE,AMP,"8 X 500 watts into 8 ohms, with DSP+DANTE","$6,829","$4,097",NA,NA,NA
568,Ottocanali 8K4,AMP,8 X 500 watts into 8 ohms,"$5,948","$3,567",NA,NA,NA
569,Ottocanali 4K4 DSP+DANTE,AMP,"8 X 250 watts into ohms, with DSP+DANTE","$5,799","$3,479",NA,NA,NA
570,Ottocanali 4K4,AMP,8 X 250 watts into ohms,"$4,918","$2,951",NA,NA,NA
571,Ottocanali 1204 DSP+ETH,AMP,"4 X 80 watts into ohms, with DSP+ETH","$3,121","$1,873",NA,NA,NA
572,Ottocanali 1204,AMP,4 X 80 watts into ohms,"$2,658","$1,595",NA,NA,NA
573,BatFormer 70V,XFORMER,70V plug-in output transformer (for use with O...,$93,$56,NA,NA,NA
574,BatFormer 100V,XFORMER,100V plug-in output transformer (for use with ...,$93,$56,NA,NA,NA
575,Mezzo 604 AD,AMP,"4 X 150 watts into ohms, with DSP+DANTE","$1,664",$998,NA,NA,NA
576,Mezzo 604 A,AMP,"4 X 150 watts into ohms, with DSP","$1,406",$844,NA,NA,NA
577,Mezzo 602 AD,AMP,"2 X 300 watts into 8 ohms, with DSP+DANTE","$1,303",$782,NA,NA,NA
578,Mezzo 602 A,AMP,"2 X 300 watts into 8 ohms, with DSP","$1,148",$689,NA,NA,NA
579,Mezzo 324 AD,AMP,"4 X 80 watts into 8 ohms, with DSP+DANTE","$1,354",$813,NA,NA,NA
580,Mezzo 324 A,AMP,"4 X 80 watts into ohms, with DSP","$1,097",$658,NA,NA,NA
581,Mezzo 322 AD,AMP,"2 X 160 watts into 8 ohms, with DSP+DANTE","$1,097",$658,NA,NA,NA
582,Mezzo 322 A,AMP,"2 X 160 watts into 8 ohms, with DSP",$942,$565,NA,NA,NA
584,I-FMR500,MIC,"Earthworks 19"" Cardioid Podium Microphone with...",$749,$458,NA,NA,NA
585,I-FMR500/HC,MIC,"Earthworks 19"" Hypercardioid Podium Microphone...",$749,$458,NA,NA,NA
586,I-FMR600,MIC,"Earthworks 23.5"" Cardioid Podium Microphone wi...",$749,$458,NA,NA,NA
587,I-FMR600/HC,MIC,"Earthworks 23.5"" Hypercardioid Podium Micropho...",$749,$458,NA,NA,NA
588,I-FMR720,MIC,"Earthworks 27"" Cardioid Podium Microphone with...",$749,$458,NA,NA,NA
589,I-FMR720/HC,MIC,"Earthworks 27"" Hypercardioid Podium Microphone...",$749,$458,NA,NA,NA